update build and install instructions
I had forgotten to update them with req tools checks

diff --git a/bin/aws-cli-mfa-zsh b/bin/aws-cli-mfa-zsh
--- a/bin/aws-cli-mfa-zsh
+++ b/bin/aws-cli-mfa-zsh
@@ -3,6 +3,31 @@
 # you MUST source this file to get the exports in your shell!
 
 
+# https://stackoverflow.com/questions/2683279/how-to-detect-if-a-script-is-being-sourced/28776166#28776166
+([[ -n $ZSH_EVAL_CONTEXT && $ZSH_EVAL_CONTEXT =~ :file$ ]] ||
+ [[ -n $KSH_VERSION && $(cd "$(dirname -- "$0")" &&
+    printf '%s' "${PWD%/}/")$(basename -- "$0") != "${.sh.file}" ]] ||
+ [[ -n $BASH_VERSION ]] && (return 0 2>/dev/null)) &&
+    SOURCED=1 || SOURCED=0
+
+
+# https://stackoverflow.com/questions/592620/how-can-i-check-if-a-program-exists-from-a-bash-script
+if ! command -v python3 >/dev/null 2>&1; then
+    echo "python3 could not be found!"
+    [[ $SOURCED -eq 1 ]] && return 0 || exit 0
+fi
+
+if ! command -v aws >/dev/null 2>&1; then
+    echo "aws could not be found!"
+    [[ $SOURCED -eq 1 ]] && return 0 || exit 0
+fi
+
+if ! command -v jq >/dev/null 2>&1; then
+    echo "jq could not be found!"
+    [[ $SOURCED -eq 1 ]] && return 0 || exit 0
+fi
+
+
 PYCODE=$(cat << EOF
 
 #!/usr/bin/env python3
@@ -128,14 +153,6 @@ EOF
 )
 
 RESPONSE=$(COLUMNS=999 /usr/bin/env python3 -c "$PYCODE" $@)
-
-
-# https://stackoverflow.com/questions/2683279/how-to-detect-if-a-script-is-being-sourced/28776166#28776166
-([[ -n $ZSH_EVAL_CONTEXT && $ZSH_EVAL_CONTEXT =~ :file$ ]] ||
- [[ -n $KSH_VERSION && $(cd "$(dirname -- "$0")" &&
-    printf '%s' "${PWD%/}/")$(basename -- "$0") != "${.sh.file}" ]] ||
- [[ -n $BASH_VERSION ]] && (return 0 2>/dev/null)) &&
-    SOURCED=1 || SOURCED=0
 
 
 if [[ "$RESPONSE" == usage* ]] ; then
